# Data Structures

## AdminUser (object)
+ `id`: `15` (number)
+ `uuid`: `91fb9777-daa9-4b4e-94c9-1673b941875c` (string)
+ `name`: `Joe Admin` (string)
+ `email`: `joeadmin@daliaresearch.com` (string)

## ResponseErrors (object)
+ errors (array[string])
