---
test:
  hosts: <%= ENV.fetch('DALIA_SECRET_HOSTS').split(",").to_s %>
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "GOOGLE_CLIENT_ID"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    mock_mode: true
    debug_mode:
  smtp:
    enabled: false
  api:
    admin_token:
      - TEST_ADMIN_TOKEN_1
      - TEST_ADMIN_TOKEN_2
    token:
      - TEST_TOKEN_1
      - TEST_TOKEN_2
development:
  hosts: <%= ENV.fetch('DALIA_SECRET_HOSTS').split(",").to_s %>
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    mock_mode: true
    debug_mode: true
  smtp:
    enabled: false
  api:
    admin_token:
      - ADMIN_TOKEN_1
      - ADMIN_TOKEN_2
    token:
      - TOKEN_1
      - TOKEN_2
staging:
  hosts: <%= ENV.fetch('DALIA_SECRET_HOSTS').split(",").to_s %>
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    graphite_host: 10.0.128.44
    graphite_port: 2003
    statsd_host: 10.0.128.44
    statsd_port: 8125
    mock_mode: false
    debug_mode: true
  smtp:
    enabled: true
    server: smtp.sendgrid.net
    port: 587
    domain: appreciationsbillboard.staging.daliaresearch.com
    user: apikey
    pass: "<%= ENV.fetch('DALIA_SECRET_SMTP_PASS') %>"
  api:
    admin_token:
      - "<%= ENV.fetch('DALIA_SECRET_API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('DALIA_SECRET_APP_TOKEN') %>"
production:
  hosts: <%= ENV.fetch('DALIA_SECRET_HOSTS').split(",").to_s %>
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    graphite_host: 10.0.0.44
    graphite_port: 2003
    statsd_host: 10.0.0.44
    statsd_port: 8125
    mock_mode: false
    debug_mode: false
  smtp:
    enabled: true
    server: smtp.sendgrid.net
    port: 587
    domain: appreciationsbillboard.daliaresearch.com
    user: apikey
    pass: "<%= ENV.fetch('DALIA_SECRET_SMTP_PASS') %>"
  api:
    admin_token:
      - "<%= ENV.fetch('DALIA_SECRET_API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('DALIA_SECRET_APP_TOKEN') %>"
