---
test:
  host: test.com
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "GOOGLE_CLIENT_ID"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  smtp:
    enabled: false
  api:
    admin_token:
      - TEST_ADMIN_TOKEN_1
      - TEST_ADMIN_TOKEN_2
    token:
      - TEST_TOKEN_1
      - TEST_TOKEN_2
development:
  host: http://railsskeleton.daliaresearch.com.pizza
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  smtp:
    enabled: false
  api:
    admin_token:
      - ADMIN_TOKEN_1
      - ADMIN_TOKEN_2
    token:
      - TOKEN_1
      - TOKEN_2
staging:
  host: http://railsskeleton.staging.daliaresearch.com
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  smtp:
    enabled: true
    server: smtp.sendgrid.net
    port: 587
    domain: railsskeleton.staging.daliaresearch.com
    user: apikey
    pass: "<%= ENV.fetch('DALIA_SECRET_SMTP_PASS') %>"
  api:
    admin_token:
      - "<%= ENV.fetch('DALIA_SECRET_API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('DALIA_SECRET_APP_TOKEN') %>"
production:
  host: http://railsskeleton.daliaresearch.com
  admin_email: it@daliaresearch.com
  google_auth:
    client_id: "193465454284-apigmm255ti8n2rb9ov2obtir6s2cdin.apps.googleusercontent.com"
    client_secret: "<%= ENV.fetch('DALIA_SECRET_GOOGLE_AUTH_CLIENT_SECRET') %>"
  smtp:
    enabled: true
    server: smtp.sendgrid.net
    port: 587
    domain: railsskeleton.daliaresearch.com
    user: apikey
    pass: "<%= ENV.fetch('DALIA_SECRET_SMTP_PASS') %>"
  api:
    admin_token:
      - "<%= ENV.fetch('DALIA_SECRET_API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('DALIA_SECRET_APP_TOKEN') %>"
