test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: dalia_appreciationsbillboard_test
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: dalia_appreciationsbillboard_development
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: db-appreciationsbillboard-stg.dalia.network
  port: 3306
  database: appreciationsbillboard
  username: daliaapp
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>

production:
  production:
    url: <%= ENV["DATABASE_URL"] %>
