test:
  adapter: mysql2
  encoding: utf8
  database: railsskeleton_test
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>

development:
  adapter: mysql2
  encoding: utf8
  database: railsskeleton_development
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>

staging:
  adapter: mysql2
  encoding: utf8
  host: db-railsskeleton-stg.dalia.network
  port: 3306
  database: railsskeleton
  username: daliaapp
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>

production:
  adapter: mysql2
  encoding: utf8
  host: db-railsskeleton-prd.dalia.network
  port: 3306
  database: railsskeleton
  username: daliaapp
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
