test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: dalia_railsskeleton_test
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: dalia_railsskeleton_development
  username: root
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: db-railsskeleton-stg.dalia.network
  port: 3306
  database: railsskeleton
  username: daliaapp
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: db-railsskeleton-prd.dalia.network
  port: 3306
  database: railsskeleton
  username: daliaapp
  password: <%= ENV.fetch('DALIA_SECRET_RAILS_DB_PASSWORD') %>
