development:
  app_name: RailsSkeleton (Development)
  monitor_mode: false

test:
  app_name: RailsSkeleton (Test)
  monitor_mode: false

staging:
  app_name: RailsSkeleton (Staging)
  monitor_mode: false

production:
  app_name: RailsSkeleton
  rules.ignore_url_regexes: ["^/health"]
  distributed_tracing.enabled: true
