development:
  app_name: AppreciationsBillboard (Development)
  monitor_mode: false

test:
  app_name: AppreciationsBillboard (Test)
  monitor_mode: false

staging:
  app_name: AppreciationsBillboard (Staging)
  monitor_mode: false

production:
  app_name: AppreciationsBillboard
  rules.ignore_url_regexes: ["^/health"]
  distributed_tracing.enabled: true
